### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by PAVAN-VANAM** [Megh2005/Med-o-Next#10]
Hello @Megh2005 

I want to work on the HomePage but you guys do not mention the specific stack used in this project whether its MERN or NEXTJS 

So I want some inputs about stack details and the home page requirements from your side. 

I want to work on this project 

Can you please assign me to this project under Gssoc_ext and Hactoberfest with level of issue

**Comment by Megh2005** [comment]
Hello @PAVAN-VANAM 
We have clearly mentioned in our readme that we are not accepting any issues regarding our homepage. Please look into the branches to create issues
