### ISSUE TITLE
Fix Scroll Animations & Enhance with  " whileInView " Method

### ISSUE THREAD

**Issue by Mallik-vinukonda** [Megh2005/Med-o-Next#100]
I’ve noticed an issue where the scroll animations on the Med-O-Next website are only working once and then stopping. To fix this, I will implement the whileInView method to ensure the animations trigger correctly when elements come into view. Additionally, I will enhance the scroll animations for smoother and more engaging transitions throughout the site.

Let me know if you'd like any further details or have specific animation preferences.

**Comment by Megh2005** [comment]
fill the issue form
