### ISSUE TITLE
[ISSUE] Adding Contact Us Page

### ISSUE THREAD

**Issue by azhar47-sk** [Megh2005/Med-o-Next#105]
### ISSUE NAME

Adding Contact Us Page

### ISSUE BRANCH

Footer

### ISSUE DESCRIPTION

Hi. I would like to add Contact Us Page in the Website. Kindly assign this Issue to me.

### YOUR APPROACH

I'll create the page using react components

### YOUR NAME

Azhar Shaikh

### YOUR GITHUB PROFILE URL

https://github.com/azhar47-sk

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
Please modify the issue 
- creating a contact us section using Firebase Realtime Database 
- fixing all minor bugs in the master branch

**Comment by gurramkarthiknetha** [comment]
assign this issue to me i will fix this.

**Comment by Megh2005** [comment]
Hey @gurramkarthiknetha 
Please raise this issue by filling the form, We will assign you
