### ISSUE TITLE
[Feature] Adding an About Us page for the websie

### ISSUE THREAD

**Issue by Ahsankhalid618** [Megh2005/Med-o-Next#107]
### ISSUE NAME

About Us page

### ISSUE BRANCH

Main

### ISSUE DESCRIPTION

I want to add an about us page for the website which should tell the end users the main objectives of your project.

### YOUR APPROACH

I'll add a new page with the same UI style or an improved if you want and optimize the page for end users

### YOUR NAME

Ahsan khalid

### YOUR GITHUB PROFILE URL

https://github.com/Ahsankhalid618

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [x] Read Documentation
- [x] Want more credentials
- [x] Other

**Comment by Megh2005** [comment]
Already assigned to someone else
