### ISSUE TITLE
Adding login and signup form along with input validations

### ISSUE THREAD

**Issue by Gauravtb2253** [Megh2005/Med-o-Next#109]
Hello
I would like to create express backend and  add login and signup forms 
I will also add input form validations 
Pls assign me

**Comment by Megh2005** [comment]
Not required right now
But you can raise another issue having the contents 
- fixing all bugs in the main branch 
- add a contact form using Firebase Realtime Database 

We will give you level 3 if you are abke

**Comment by Gauravtb2253** [comment]
Can you pls tell exactly what you need
