### ISSUE TITLE
ADD: Admin Page to Med-o-Media feature

### ISSUE THREAD

**Issue by Nkovaturient** [Megh2005/Med-o-Next#111]
### ISSUE NAME

Enhancing user experience by integrating a  Health Article Submission Form.

### ISSUE BRANCH

Med-o-Media

### ISSUE DESCRIPTION

**Task:-**

-  Verified Health Article Submission Form ✅

**About:-**

- The Health Article Submission Form is designed for authenticated users who can post health-related articles after verification. It will allow users to input article titles, descriptions, categories/tags, and upload images. 

- The articles are moderated and published upon approval. This feature ensures that only verified, high-quality health content is shared on the platform.

### YOUR APPROACH

Form Creation:

1. Build the form with fields like title, category (mental health, fitness, etc.), article content, image upload, and tags.
2. Validate user inputs using form libraries like Formik or React Hook Form.
3. Article Submission & Verification:
4. Submit the form data to the firestore.
5. Save articles as "pending" in the database.
6. **(Build an admin dashboard where moderators can review and approve/reject articles before publishing to maintain the credibility of the web app)**

### YOUR NAME

Neha Kumari

### YOUR GITHUB PROFILE URL

https://github.com/Nkovaturient

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [ ] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by iSubhamMani** [comment]
@Nkovaturient you're assigned

**Comment by Nkovaturient** [comment]
Sure.
Thanks! @iSubhamMani   😄

**Comment by Nkovaturient** [comment]
Update: 


https://github.com/user-attachments/assets/70730910-b573-4f81-a5af-08b7ce81ed64


Should I create a PR..?

**Comment by iSubhamMani** [comment]
Great work 👍 yes you can create a PR. Will review it

**Comment by Megh2005** [comment]
We have merged your PR
