### ISSUE TITLE
[ISSUE] Add a FAQ section 

### ISSUE THREAD

**Issue by yeshwanth-ds** [Megh2005/Med-o-Next#113]
### ISSUE NAME

Add a FAQ section

### ISSUE BRANCH

Main

### ISSUE DESCRIPTION

Add a FAQ section with dropdown answer section

### YOUR APPROACH

make a responsive drop down with a relaveant and most asked FAQs

### YOUR NAME

Yeshwanth

### YOUR GITHUB PROFILE URL

https://github.com/yeshwanth-ds

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [X] Other

**Comment by iSubhamMani** [comment]
@yeshwanth-ds you're assigned

**Comment by meghanakn473** [comment]
@iSubhamMani  please assign this issue to me as there is no respone from @yeshwanth-ds

**Comment by Megh2005** [comment]
@meghanakn473 
This is not the process. We have to give him 72hrs.

**Comment by Megh2005** [comment]
@yeshwanth-ds what's the status?

**Comment by Megh2005** [comment]
We are closing the issue as there is no response from your side
