### ISSUE TITLE
[ISSUE] Med-o-coach responding twice

### ISSUE THREAD

**Issue by PalakMis1808** [Megh2005/Med-o-Next#116]
### ISSUE NAME

Improve response from MED-O-COACH

### ISSUE BRANCH

Med-o-Coach

### ISSUE DESCRIPTION

When asked from Medical Condition in a specific language, it should give response in that language only,
when asked for Medical Guidance in English, it provided with the same response twice.

### YOUR APPROACH

# Train the Model

I will train the model to respond in the selected language only.

### YOUR NAME

Palak Mishra

### YOUR GITHUB PROFILE URL

https://github.com/PalakMis1808

### Please select the applicable categories

- [ ] Hacktoberfest
- [X] GSSOC'24 Extended
- [ ] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
It's planned 
It's not a glitch, we are intentionally generating bilingual response
