### ISSUE TITLE
[ISSUE] No hover effect on the buttons

### ISSUE THREAD

**Issue by MohitSrivastava22** [Megh2005/Med-o-Next#117]
### ISSUE NAME

There is various button on there website but they don't have hover effect on them

### ISSUE BRANCH

Med-o-shop,Med-o-lens,Med-o-chat,Med-o-Ai

### ISSUE DESCRIPTION

There are multiple buttons on the website, but they do not have the desired hover effect. The buttons are expected to change style, such as the text color or background color, when hovered over, but this effect is somewhere missing. 

### YOUR APPROACH

The goal is to create a hover effect where the button changes its background color and appears to elevate as if it's moving outwards in the z-plane. This effect combines both a visual style change (color) and a depth illusion (shadow and movement).

### YOUR NAME

Mohit Srivastava

### YOUR GITHUB PROFILE URL

https://github.com/MohitSrivastava22

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
We don't need this right now
