### ISSUE TITLE
[ISSUE] Adding of favicon to the main page

### ISSUE THREAD

**Issue by jayanththalla** [Megh2005/Med-o-Next#118]
### ISSUE NAME

Add the favicon 

### ISSUE BRANCH

Main

### ISSUE DESCRIPTION

The favicon of the main page is to be added 

### YOUR APPROACH

I will add favicon to page by navbar icons

### YOUR NAME

Jayanth Thalla

### YOUR GITHUB PROFILE URL

https://github.com/jayanththalla

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [X] Other

**Comment by Megh2005** [comment]
Not required right now
