### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Megh2005/Med-o-Next#119]
### ISSUE NAME

-

### ISSUE BRANCH

med-o-next

### ISSUE DESCRIPTION

<img width="698" alt="Screenshot 2024-10-18 at 5 05 39 PM" src="https://github.com/user-attachments/assets/0a139730-f4d0-444d-ae71-eeb2f1cd8829">

### YOUR APPROACH

I want to add a page to showcase all the contributors of this website.
@Megh2005 can you assign me this issue.

### YOUR NAME

T Rahul Prabhu

### YOUR GITHUB PROFILE URL

https://github.com/T-Rahul-prabhu-38

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
It's our job. We appreciate your effort. 
Our team is already making this
