### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by saras-69** [Megh2005/Med-o-Next#125]
### ISSUE NAME

Make Navbar Components Sticky on Scroll

### ISSUE BRANCH

Nav

### ISSUE DESCRIPTION

Currently, the navigation bar and header scroll out of view as users move down the webpage, affecting usability. Making the navbar sticky will improve user experience by keeping the navigation elements accessible at all times.

Steps to Reproduce:

Open the website on the main branch.
Scroll down the webpage.
Observe that the navbar and header are no longer visible.

### YOUR APPROACH

I will make the navbar and header sticky using CSS, ensuring they remain fixed at the top of the viewport during scrolling

### YOUR NAME

Saraswati Chandra 

### YOUR GITHUB PROFILE URL

https://github.com/saras-69

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [X] Other

**Comment by Megh2005** [comment]
Already assigned to someone

**Comment by saras-69** [comment]
@Megh2005 still not resolved

**Comment by Megh2005** [comment]
We have given him a warning period of 24hrs
After that, this will be assigned to you as `level 1`

**Comment by saras-69** [comment]
@Megh2005 still not resolved
