### ISSUE TITLE
[ISSUE] Scroll to top feature

### ISSUE THREAD

**Issue by meghanakn473** [Megh2005/Med-o-Next#126]
### ISSUE NAME

.

### ISSUE BRANCH

.

### ISSUE DESCRIPTION

scroll to top button helps user to navigate to top of page easily

### YOUR APPROACH

.

### YOUR NAME

Meghana

### YOUR GITHUB PROFILE URL

https://github.com/meghanakn473

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [ ] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by meghanakn473** [comment]
@Megh2005 please assign this issue to me under level 3, gssoc-extd

**Comment by Megh2005** [comment]
_we already have this. Just the deployment is left._
