### ISSUE TITLE
[ISSUE] Creating Backend Template for further development and adding mongoose schema for users

### ISSUE THREAD

**Issue by IkkiOcean** [Megh2005/Med-o-Next#132]
### ISSUE NAME

Creating backend and schema for users

### ISSUE BRANCH

main

### ISSUE DESCRIPTION

We need to establish a backend template to streamline future development for the application. Additionally, we should implement a Mongoose schema for user management, which will allow us to manage user authentication, profiles, and permissions.

### YOUR APPROACH

- I will be making backend in Nodejs
- for database I will be using MongoDB

### YOUR NAME

Vivek prakash

### YOUR GITHUB PROFILE URL

https://github.com/IkkiOcean

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [ ] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
The landing section is planned as a static section 
So we don't need any backend facility for this
