### ISSUE TITLE
[ISSUE] Updation in code of conduct file

### ISSUE THREAD

**Issue by Nikhil0-3** [Megh2005/Med-o-Next#134]
### ISSUE NAME

Updation of code_of_conduct file

### ISSUE BRANCH

documentation

### ISSUE DESCRIPTION

There is no any proper information about 
Our Pledge
Our Standards
Enforcement Responsibilities
Enforcement Guidelines
Expand Correction to include guidance for future behavior.

Also,
   by Adding the different symbols it looks more creative.

### YOUR APPROACH

here are the some topics i want to add -

Our Pledge

Our Standards:
Add Encouraging Mentorship under positive behavior.
unacceptable behavior.

Enforcement Responsibilities:
Clarify communication of moderation actions.

Enforcement Guidelines:
Expand Correction to include guidance for future behavior.

Also, by Adding the different symbols it looks creative.

### YOUR NAME

Nikhil More

### YOUR GITHUB PROFILE URL

https://github.com/Nikhil0-3

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
It's a level1 issue

**Comment by Megh2005** [comment]
You are assigned

**Comment by Nikhil0-3** [comment]
> pls assign this issue

Its already done bro.
