### ISSUE TITLE
[ISSUE]: Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Megh2005/Med-o-Next#135]
### ISSUE NAME

Documentation Update

### ISSUE BRANCH

CONTRIBUTING.md

### ISSUE DESCRIPTION

The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

### YOUR APPROACH

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

### YOUR NAME

MILAN P SAMUEL

### YOUR GITHUB PROFILE URL

https://github.com/milansamuel609

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
It's a level 1 issue

**Comment by Megh2005** [comment]
You are assigned

**Comment by milansamuel609** [comment]
> It's a level 1 issue

Sure 👍
