### ISSUE TITLE
UI UX Enhancements | Addition of ProgressBar | That will represent the Current Depth of the Webpage

### ISSUE THREAD

**Issue by Shariq2003** [Megh2005/Med-o-Next#137]
I want to add a progress bar that will show the current depth of the webpage, just like GSSOC website

![image](https://github.com/user-attachments/assets/057676e2-0bab-4a96-8137-fccaa16eb6d6)

Look at the top, an orange line

**Comment by Megh2005** [comment]
You are assigned

**Comment by DINES-04** [comment]
i want to impove the alignment and work are cutted so, i want make to read easable:
![image](https://github.com/user-attachments/assets/cea5f88e-17a4-4b6b-b653-c07b128d4320)

@Shariq2003 Could you please assign this home page design enhancement task to me and label it for contribution? I’m excited to start working on it. Thank you!

**Comment by Shariq2003** [comment]
> i want to impove the alignment and work are cutted so, i want make to read easable: ![image](https://private-user-images.githubusercontent.com/153375074/380423866-cea5f88e-17a4-4b6b-b653-c07b128d4320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDc5MTksIm5iZiI6MTcyOTk0NzYxOSwicGF0aCI6Ii8xNTMzNzUwNzQvMzgwNDIzODY2LWNlYTVmODhlLTE3YTQtNGI2Yi1iNjUzLWMwN2IxMjhkNDMyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzAwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDZkNTk1ZDMyN2I5YWNjZTc2NmUwM2JmMjRkNDgwOTNjMTQ1YmE3ZTRiMGJlYzA4YjRkZGM4NWJhYzVkYWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.juZ_LkExARw9CX2juByaHL4wM7AFq5KiXyuuAu8Lc3k)
> 
> @Shariq2003 Could you please assign this home page design enhancement task to me and label it for contribution? I’m excited to start working on it. Thank you!

@DINES-04 bro, I am not Project 😅
Please ask @Megh2005 sir

**Comment by Shariq2003** [comment]
@Megh2005 sir, could u please let me know which branch of this repo contains the website's code.
Also Sorry for getting late to start working on this issue, as I was stuck in the backlogs.

**Comment by DINES-04** [comment]
> [Megh2005](/Megh2005)

thanks for clarify me

**Comment by DINES-04** [comment]
@Megh2005 Could you please assign this home page design enhancement task to me and label it for contribution? I’m excited to start working on it. Thank you!

**Comment by Shariq2003** [comment]
> @Megh2005 Could you please assign this home page design enhancement task to me and label it for contribution? I’m excited to start working on it. Thank you!

raise an issue and comment there bro 😊
