### ISSUE TITLE
Addition of the navbar

### ISSUE THREAD

**Issue by Nvntdad** [Megh2005/Med-o-Next#14]
can you please assign it to me for introducing the navbar.
and please add gssoc and hacktoberfest label

**Comment by Megh2005** [comment]
Of which branch?? 
Please send us detailed explanation of your issue

**Comment by Nvntdad** [comment]
i was just wandering on the website, i think navbar on the home page should be added for better user experience. which contains different buttons and as well logo on the left side.

**Comment by Megh2005** [comment]
Please read the readme, we don't want any contribution in the landing screen.
