### ISSUE TITLE
The homepage is not properly responsive according to smartphone screens

### ISSUE THREAD

**Issue by Nvntdad** [Megh2005/Med-o-Next#15]
the issue that is recognised by me is the text of the description is not responsive according to the smartphones, it is kind of hidden in the  in the side bar.

**look in this picture** 

![mad-o-next](https://github.com/user-attachments/assets/3786be35-58d0-4d97-982e-866fb2bb6392)

please assign this task to me.

**Comment by Megh2005** [comment]
Please read the readme 
We don't want any contribution in the home or landing screen

**Comment by Megh2005** [comment]
We don't want any contribution to the landing screen 
It's clearly mentioned in the readme file
