### ISSUE TITLE
[ISSUE] Implement Carousel for User Reviews

### ISSUE THREAD

**Issue by IkkiOcean** [Megh2005/Med-o-Next#157]
### ISSUE NAME

A Carousel to show reviews of the users

### ISSUE BRANCH

Main

### ISSUE DESCRIPTION

We need to implement a carousel component to display user reviews on the homepage. This will enhance the user experience by allowing visitors to easily browse through reviews without overwhelming them with too much information at once.

### YOUR APPROACH

- The carousel should automatically cycle through user reviews every 5 seconds.
- Users should be able to manually navigate through reviews using next and previous buttons.
- Each review should display the user's name, review text, and a rating (if applicable).
- The carousel should be responsive and visually appealing, maintaining usability across different devices.

### DEMO Video

https://github.com/user-attachments/assets/77840b4f-faf7-48dc-aac4-57d1837f06cc

### YOUR NAME

Vivek Prakash

### YOUR GITHUB PROFILE URL

https://github.com/IkkiOcean

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [ ] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by IkkiOcean** [comment]
@Megh2005 hey. can you please explain why you marked it as completed. I didnt find this feature on the website

**Comment by Megh2005** [comment]
Please read the pinned issue

**Comment by Megh2005** [comment]
We have paused our contribution process
