### ISSUE TITLE
ADD CICD Github Workflow for easy integration 

### ISSUE THREAD

**Issue by shubhagarwal1** [Megh2005/Med-o-Next#160]
**Workflow to be implemeted**

- Auto Comment on Issue
- Auto Comment on PR
- Auto Comment on PR Merge
- Auto Label Issue
- Auto Label Issues
- Auto Label PRs
- Close Issues on PR Merge
- Close Old Issues
- Close Stale PRs
- Comment on Issue Close

**Comment by Megh2005** [comment]
@shubhagarwal1 
YOU ARE ASSIGNED WITH `LEVEL 2`

**Comment by shubhagarwal1** [comment]
hey @Megh2005 do you want all of them metioned in the desc.

**Comment by Megh2005** [comment]
* Auto Comment on PR Merge
* Close Issues on PR Merge
* Close Old Issues
* Close Stale PRs
* Comment on Issue Close

**Comment by Megh2005** [comment]
Only these 5 are enough

**Comment by shubhagarwal1** [comment]
hey @Megh2005 it is completed can you please rview the PR

**Comment by shubhagarwal1** [comment]
> * Auto Comment on PR Merge
> * Close Issues on PR Merge
> * Close Old Issues
> * Close Stale PRs
> * Comment on Issue Close

It is PR #173

**Comment by Megh2005** [comment]
Merged
Assigned to you with proper labels

**Comment by shubhagarwal1** [comment]
> Merged Assigned to you with proper labels

Hey do we have any other tasks i can do it for now possibley

**Comment by Megh2005** [comment]
NO 
Thank you so much. 
You can check the [Pinned Issue](https://github.com/Megh2005/Med-o-Next/issues/170#issue-2616757367)
