### ISSUE TITLE
To impove the alignment and display full word to read for the customer

### ISSUE THREAD

**Issue by DINES-04** [Megh2005/Med-o-Next#168]
To impove the alignment and word are cutted so, i want make to read easable:
![image](https://github.com/user-attachments/assets/cea5f88e-17a4-4b6b-b653-c07b128d4320)

@Megh2005 , Could you please assign this home page design enhancement task to me and label it for contribution? I’m excited to start working on it. Thank you!

_Originally posted by @DINES-04 in https://github.com/Megh2005/Med-o-Next/issues/137#issuecomment-2439573391_

**Comment by DINES-04** [comment]
and can you assign me for the impove the alignment and increase readability with labels

**Comment by DINES-04** [comment]
@sanjay-kv this also mentor is not replay

**Comment by sanjay-kv** [comment]
give some time, it has been only 1 day
