### ISSUE TITLE
Creation of a very good readme file for this repository 

### ISSUE THREAD

**Issue by Megh2005** [Megh2005/Med-o-Next#17]
# Readme file modification & documentation enhancement

We want someone to change or modify the entire **Readme.md** file. He / She should do all the required stylings. We want a proper readme file having all the sections required i.e contributors guide, star count, issue template etc. everything 
We are going to give a `Level 3` tag along with all required labels 
Interested people should join this discussion giving links to some of the readme files, designed by him / her

**Comment by Kartikey2011yadav** [comment]
can i do this readme restyling work?

**Comment by Megh2005** [comment]
If you take this responsibility, you have to do the complete reconstruction of the 3 readme files
One for the main branch
One for the Med-o-Chat branch
One for the Med-o-Lens branch

**Comment by Rizvi-Faiz** [comment]
i would like to work on this issue

**Comment by Rizvi-Faiz** [comment]
@Megh2005 can you assign this issue to me

**Comment by Megh2005** [comment]
Okay
before that give me your official email id
I will mail you the required credentials and guidelines

**Comment by Rizvi-Faiz** [comment]
rizvifaiz1073@gmail

**Comment by Megh2005** [comment]
- Modify the **Key Features** section
- Make the **Special Attributes** section detailed
- Beautify the **Contribution Guide** section
## Please don't modify any other sections in the main readme file

**Comment by Megh2005** [comment]
> rizvifaiz1073@gmail

Email Not required. 
```bash
Name : 
GitHub User Name : 
```

Just fill this form

**Comment by Rizvi-Faiz** [comment]
Name Rizvi Faiz
Github @Rizvi-Faiz

**Comment by Rizvi-Faiz** [comment]
@Megh2005  I asked you why you did'nt assign me i also gave you my Name and github username

**Comment by Megh2005** [comment]
there was a mistake, now the issue is assigned to you

**Comment by Rizvi-Faiz** [comment]
@Megh2005  in the med-o-lens branch there is no readme file should i make new one similar to the med-o-next which you merged to main branch
