### ISSUE TITLE
[doc]add README.md with GitHub repo stats

### ISSUE THREAD

**Issue by REHAN-18** [Megh2005/Med-o-Next#174]
### ISSUE NAME

 README.md

### ISSUE BRANCH

DOC

### ISSUE DESCRIPTION

The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions in the repository at a glance.

### YOUR APPROACH

Steps to Implement:

1-Create a table in the README.md file displaying the following repository statistics:
Stars
Forks
Open Issues
Open Pull Requests
Closed Pull Requests
2-Use markdown syntax to include badges or icons for each statistic, along with dynamic links to the corresponding sections of the repository.
<img width="609" alt="Screenshot 2024-10-29 at 11 59 48 AM" src="https://github.com/user-attachments/assets/6aebd46a-169f-43da-9f85-5c5d6734200c">

### YOUR NAME

MD REHAN

### YOUR GITHUB PROFILE URL

https://github.com/REHAN-18

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
@REHAN-18 you are assigned

**Comment by REHAN-18** [comment]
@Megh2005  done this  see pr #182 & merge it

**Comment by Megh2005** [comment]
Merged
