### ISSUE TITLE
[Improvements][New Feature] Enhance Target Languages Dropdown UI & Add Voice Response

### ISSUE THREAD

**Issue by J-B-Mugundh** [Megh2005/Med-o-Next#22]
Description:

We need to improve the user experience of the target languages dropdown in the Med-O-Lens application. Specifically, the UI should be enhanced to be more intuitive and user-friendly. Additionally, a voice response feature needs to be integrated for a more seamless interaction with the application.

Action Required:

- Redesign and optimize the target languages dropdown UI.
- Add a voice response feature to enhance accessibility and user engagement.

Benefits:

- Improved User Experience: A more intuitive dropdown will enhance ease of use and navigation.
- Increased Accessibility: The voice response feature will cater to users with varying abilities, making the application more inclusive.
- Better Engagement: Voice responses can create a more interactive and engaging experience for users.

Expected Timeline: 1-2 days

![image](https://github.com/user-attachments/assets/5734cee9-2e1d-4e93-9c04-477dadaf04f6)

Labels:

- gssoc-extd
- hacktoberfest
- level2/level3

**Comment by J-B-Mugundh** [comment]
@Megh2005 Please assign me this issue! I'm new to open source contributions and would really like to contribute to this project. So, let me start with this issue.

**Comment by Megh2005** [comment]
Start Working please, you have been assigned

**Comment by Megh2005** [comment]
Send me your GitHub details

**Comment by Megh2005** [comment]
Give your GitHub profile URL

**Comment by J-B-Mugundh** [comment]
> Send me your GitHub details

https://github.com/J-B-Mugundh/Med-o-Next

**Comment by Megh2005** [comment]
Your GitHub profile URL along with your full name 
Like 
Megh Deb 
https://github.com/Megh2005

**Comment by J-B-Mugundh** [comment]
> Your GitHub profile URL along with your full name Like Megh Deb https://github.com/Megh2005

My full name: J B Mugundh

Profile: https://github.com/J-B-Mugundh
Repo: https://github.com/J-B-Mugundh/Med-o-Next
Branch: https://github.com/J-B-Mugundh/Med-o-Next/tree/Med-o-Lens

**Comment by J-B-Mugundh** [comment]
May I know what for is this bro?

**Comment by J-B-Mugundh** [comment]
> Updating the contributors table in readme as well as to assign you proper score It will be a reference

Oh okay! thank you 😊
