### ISSUE TITLE
Enhancements for MED-O-COACH: Input Validation, UX Improvements, and Personalization Features

### ISSUE THREAD

**Issue by Tanmaykhandelwal76** [Megh2005/Med-o-Next#26]
Name : Tanmay Khandelwal
Github username : Tanmaykhandelwal76

**Branch name :** Med-o-Coach

**Issue title :** MED-O-COACH: Input Validation, UX Improvements, and Personalization Features

**Issue description :**
**1. Input Validation & Error Handling:**
Ensure proper validation for all user inputs. For example:
 Age: If age is above a certain threshold (e.g., 120), show a warning or validate accordingly.
 Weight & Height: Validate for realistic ranges, and handle cases where the user enters extreme values.
**2. Enhance User Experience:**
Progress Indicator: When the API is called, show a loading spinner or progress bar to indicate that the system is fetching recommendations.
Auto-scroll: Automatically scroll to the recommendations section when results are generated, so the user doesn't need to manually scroll down.
**3. Improved AI Prompts:**
Add more details in the AI prompt to make the health recommendations more personalized based on input (e.g., weight, height, and specific disease).
Allow users to specify goals such as weight loss, muscle gain, or stress reduction, and reflect this in the prompt.
**4. More Flexible Language Options:**
Instead of hardcoding the translate_text function to always use English as the source language, allow users to specify their input language if needed, especially for multi-language support.
**5. Add More Health Metrics:**
 Ask users for additional health-related information, such as their activity level (sedentary, moderately active, very active), and dietary preferences (vegetarian, vegan, keto, etc.), to tailor recommendations better.

GSSOC 24 EXTENDED : YES

**Comment by Tanmaykhandelwal76** [comment]
Please assign me these issues. I'll be happy to work upon them.

**Comment by Megh2005** [comment]
I will be happy to assign you this
Fill the issue template please

**Comment by Tanmaykhandelwal76** [comment]
I have already listed in issue template format only, should i write the proposed solution also in detail or is this fine ?

**Comment by Megh2005** [comment]
No just edit your last one
Add your name and GitHub user name

**Comment by Tanmaykhandelwal76** [comment]
please check is this fine?

**Comment by Megh2005** [comment]
Cool
You can initiate your work
Make it sure that you are working along the guidelines

**Comment by Megh2005** [comment]
# `48 hours passed, but you haven't shared any progress report or response to my comment; We will wait 24 hours more before closing the issue`
@Tanmaykhandelwal76

**Comment by Megh2005** [comment]
> [!Warning]
> **We are closing this issue along with all the labels due to unavailability of response from your side
Thank you so much for showing interest**
