### ISSUE TITLE
Creating a New Landing Page

### ISSUE THREAD

**Issue by Megh2005** [Megh2005/Med-o-Next#33]
- CREATE A NEW LANDING PAGE
- A VERY ATTRACTIVE FRONTEND IS REQUIRED
- IT WILL BE STATIC IN NATURE
- TAKE INSPIRATION FROM THE [PRESENT DEPLOYMENT](https://azure-darling-860166.framer.app)
- USE OF NEXT JS & THREE.JS IS EXPECTED
- **LEVEL 1** = BASIC REACT / NEXT LANDING PAGE
- **LEVEL 2** = USAGE OF FIREBASE TO CREATE A CONTACT FORM ALONG WITH LEVEL 1 TARGET
- **LEVEL 3** = MAKING A 3D LANDING PAGE WITH REACT THREE FIBRE / THREE JS WITH A CONTACT FORM USING FIREBASE

## BEST WISHES FROM TEAM TJP
![TJP](https://github.com/user-attachments/assets/32ebac8c-313e-44b2-a08d-65ed022883a0)

**Comment by viveksarkar0** [comment]
hey you want a the landing page of med- o-next if yes i can make you for this  please assing me and give me show more instruction so i can give you better result

**Comment by Megh2005** [comment]
Just tell me what kind of instruction do you want??

**Comment by viveksarkar0** [comment]
like you want exact copy of medo next landing page on next js

**Comment by Megh2005** [comment]
No, we want some enhancement, see the levels and descriptions that I have mentioned. We don't want copy. Just take the gist concept from our present deployment. And design with your own imagination 
Follow the level description mentioned over

Nake sure you fill the issue template form present in the readme file. Also mention that in which level you want to work

**Comment by Kaif9999** [comment]
hey @Megh2005 i want to create a next.js landing page for med-o-next can you please assign it to me under level 1 gssoc-ext

**Comment by Megh2005** [comment]
@viveksarkar0 as you haven't responded , I am assigning this to @Kaif9999 


@Kaif9999 build it on Next JS and Tailwind css.

**Comment by Megh2005** [comment]
# **```Make sure to hit this PR in the main branch```**

**Comment by Kaif9999** [comment]
I will fork it now and start creating it soon

**Comment by Megh2005** [comment]
Everything thing alright @Kaif9999 ?? 
Any problem just hit a message to @Megh2005 or @iSubhamMani

**Comment by Kaif9999** [comment]
@Megh2005 I'm working on it will update you with the first build in the morning from there I can raise a PR after the changes if you have any

**Comment by Megh2005** [comment]
Just tag @iSubhamMani 
He will take care and validate everything

**Comment by Kaif9999** [comment]
[Screencast from 2024-10-08 05-14-51.webm](https://github.com/user-attachments/assets/f3b0c1a9-352d-4fb7-a69d-81a4661ff19f)
you can have the look at the website i have created if you allow i will raise a PR or if you have any suggesstion please suugest me so i can raise a PR and complete this @Megh2005 @iSubhamMani

**Comment by Megh2005** [comment]
No need to implement auth
- Please create a contact us section using Firebase Realtime Database 
- If you can, please add a light and dark mode toggle

**Comment by Kaif9999** [comment]
hey i have added the light and dark mode toggle, but i can't add contact us page as of now , allow me to raise a PR

**Comment by Megh2005** [comment]
Sure, give your PR to the main branch

**Comment by Kaif9999** [comment]
Ok raising the PR to the main branch now

**Comment by Megh2005** [comment]
cool

**Comment by Megh2005** [comment]
@Kaif9999 please do a sync because I have added some changes to it

**Comment by Megh2005** [comment]
Okay
But I have edited the readme few hours ago
It can cause a merge conflict if you don't run a sync

**Comment by Kaif9999** [comment]
Ok I will run sync, if you want in next pr I can have contact form with firebase, for level 2

**Comment by Megh2005** [comment]
Not required
Thanks a lot

**Comment by Kaif9999** [comment]
hey @Megh2005 @iSubhamMani i have raised a PR please merge it
