### ISSUE TITLE
Enhancements for Med-o-Chat: Sending messages with ENTER key, message editing and deleting

### ISSUE THREAD

**Issue by Dyslex7c** [Megh2005/Med-o-Next#34]
Issue Title : Med-o-Chat: sending messages with ENTER key, message editing and deleting
Issue Description : 
Implement functionality allowing users to send messages instantly by pressing the ENTER key. Additionally, provide users with the ability to edit or delete their sent messages.
Issue Branch : Med-o-Chat
Your Approach : 
Add event listener for ENTER key press. For the latter one, I will look into the project and decide.
Your Name : Ritesh Das
GitHub User Name : Dyslex7c

**Comment by Megh2005** [comment]
Please go for work.
Please send a message over here before sending **`Pull Request`**
I have some **`Guidelines`** for you

**Comment by Dyslex7c** [comment]
can someone help me out in setting up the firebase config.ts file? I have included my API key but still getting error

**Comment by iSubhamMani** [comment]
@Dyslex7c here is the .env example: 
We're using Pusher, so please make an account over there and put the credentials. The other credentials are hopefully straight forward. Let me know if you face any further issue

NEXT_PUBLIC_JWT_SECRET=
NEXT_PUBLIC_MONGODB_URI = 

NEXT_PUBLIC_PUSHER_APP_ID = ""
NEXT_PUBLIC_PUSHER_APP_KEY = ""
NEXT_PUBLIC_PUSHER_APP_SECRET = ""

NEXT_PUBLIC_GEMINI_API_KEY = ""

NEXT_PUBLIC_FIREBASE_API_KEY = ""

**Comment by iSubhamMani** [comment]
> can someone help me out in setting up the firebase config.ts file? I have included my API key but still getting error

the API key is included in the .env. Probably that is why you're facing the issue

**Comment by Dyslex7c** [comment]
yeah I have included the API key in my .env file only

**Comment by iSubhamMani** [comment]
> yeah I have included the API key in my .env file only

what's the error showing?

**Comment by Dyslex7c** [comment]
![image](https://github.com/user-attachments/assets/b90aba4c-4b91-44da-9212-0547d180f5a3)

**Comment by iSubhamMani** [comment]
> ![image](https://private-user-images.githubusercontent.com/98543992/373926645-b90aba4c-4b91-44da-9212-0547d180f5a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxOTY0MDgsIm5iZiI6MTcyODE5NjEwOCwicGF0aCI6Ii85ODU0Mzk5Mi8zNzM5MjY2NDUtYjkwYWJhNGMtNGI5MS00NGRhLTkyMTItMDU0N2QxODBmNWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA2MjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZmU1MTcxZGQ3YWFiOWFjYWVkMTk3NzU3ZjdlMjEzM2I4Njg4YzRiZTAzY2RiMmM2OGJmMzBkZTAxMGI0OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xy-eGWutK9ryu-qU6M3fA-I7xzwqWY8-5w55tc9heBQ)

any more detailed error in the logs?

**Comment by Dyslex7c** [comment]
And in pusher, should I select channels or beams?

**Comment by iSubhamMani** [comment]
> And in pusher, should I select channels or beams?
> 
> And that error is gone now

Channels

**Comment by Dyslex7c** [comment]
error signing in

in logs it's showing that firebase api key is not valid although I did generate one. it starts like this - "--------BEGIN PRIVATE KEY-----------\n...

**Comment by iSubhamMani** [comment]
> error signing in
> 
> in logs it's showing that firebase api key is not valid although I did generate one. it starts like this - "--------BEGIN PRIVATE KEY-----------\n...

That shouldn't happen, have you included the key in a string?

**Comment by Dyslex7c** [comment]
yup I have

**Comment by iSubhamMani** [comment]
If you're facing the issue while loggin in then have you enabled google login in firebase?

**Comment by Dyslex7c** [comment]
yeah I have enabled still not working

**Comment by iSubhamMani** [comment]
> yeah I have enabled still not working
> 
> Oh I need to change the config.ts file with my creds that's why it's not working
> 
> also there is an API key in my project settings, should I use that or the private key? And where do I find appId after messaging senderId?

After creating a firebase project you should get a config file, just copy that entire thing in the config.ts file and make sure to export db just like how i have done. All your problems should go away

**Comment by iSubhamMani** [comment]
If you're still facing issue dm me your config.ts file at manisubham09@gmail.com

**Comment by Dyslex7c** [comment]
Done, now how do I start a dummy chat?

**Comment by iSubhamMani** [comment]
You gotta login with another account (use another browser if possible) and then search for that user and invite him. Once the other user accepts it, a new chat should be created. 

One more thing: the app may be a little buggy, cause pusher sometimes doesn't work properly

**Comment by Dyslex7c** [comment]
I see, thanks for the information

**Comment by Dyslex7c** [comment]
@iSubhamMani send message using enter key and delete message is done, now tell me how do I update the UI, if there is any figma file for reference or anything else

**Comment by Dyslex7c** [comment]
And @Megh2005 I'm nearing completion so you can let me know the guidelines before I open PR

**Comment by Megh2005** [comment]
At first give your PR to the main branch. I will merge it and revert it back again.
Then you can give your another PR to the branch `Med-o-Chat`

**Comment by Megh2005** [comment]
@Dyslex7c don't need to think much about designs and UI
Make sure, you have added the proposed features
We will modify the UI if required

**Comment by Dyslex7c** [comment]
@Megh2005 how do I give PR to the main branch? I haven't changed anything in the main branch

**Comment by Megh2005** [comment]
Directly give PR to the required branch
