### ISSUE TITLE
Add hover effects to buttons

### ISSUE THREAD

**Issue by devarsheecodess** [Megh2005/Med-o-Next#35]
plz assign me this task with gssoc-ext,hacktoberfest-accepted and level2 label.

**Comment by geetanjalidubey9** [comment]
i would really like to work on this.pls assign this task to me

**Comment by Megh2005** [comment]
Please fill the issue template

**Comment by Megh2005** [comment]
Hey @geetanjalidubey9 and @devarsheecodess 
I am closing the issue as both of you have not given any response.
