### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by devarsheecodess** [Megh2005/Med-o-Next#36]
I want to improve the footer of this page as it lacks UI. Assign me this task with gssoc-ext, hacktoberfest-accepted and level2 label

**Comment by Megh2005** [comment]
Please fill the issue template first
It's given in the readme file

**Comment by devarsheecodess** [comment]
Issue Title : Improve footer
Isuue Description : The footer is looking basic with minimal design
Issue Branch : main
Your Approach : Adding project name to bottom right and replacing github,email button with logos. Also write "Made with ❤️ by @Megh2005 " at bottom of footer
Your Name : Devarshee
GitHub User Name : @devarsheecodess

**Comment by Megh2005** [comment]
The landing page is being rebuilt by one contributor. 
Sorry I can't assign this to you
