### ISSUE TITLE
ADD:  Med-o-Media Feature 

### ISSUE THREAD

**Issue by Nkovaturient** [Megh2005/Med-o-Next#37]
Hello there @Megh2005 , @iSubhamMani  😀🌟
After surfing through your awe-struck, intuitively designed and  feasibly available web app, I felt the need for addition of these  MED-O-MEDIA feature.

**Issue Description**:  
The Med-o-Media feature will allow users to stay updated on the latest health news, trends, and medical breakthroughs. It will provide a customizable feed based on user preferences and deliver detailed articles written by certified health experts and doctors. The feature will enhance the user experience by offering a tailored, informative, and expert-driven media section in the MED-O-NEXT web app.

**Issue Branch**:  (to integrate)
`feature/med-o-media`

**My Approach**:  
1. Design and implement a customizable health topics feed that users can personalize based on their interests.
2. Build API Endpoints: Use Express.js to create endpoints for fetching certified health articles. Integrate third-party APIs (e.g., health news) or custom content from DB.
3. To  develop an intuitive UI (tailwindcss/framer) to display trending health news and medical breakthroughs dynamically.
4.  Integrate filters allowing users to explore specific health categories and view detailed articles in a clean, user-friendly format.
5.  Testing the feature thoroughly to ensure accuracy, efficiency, and smooth user interaction.

**My Name**:  
Neha Kumari

**GitHub User Name**:  
Nkovaturient

**Comment by iSubhamMani** [comment]
Hi @Nkovaturient very bold of you to think about this feature, but you don't have to tag everyone, me and @Megh2005 are the only collaborators. I'm assigning this issue to you

**Comment by Nkovaturient** [comment]
> Hi @Nkovaturient very bold of you to think about this feature, but you don't have to tag everyone, me and @Megh2005 are the only collaborators. I'm assigning this issue to you

Sure, Delighted to hear your response. I will kickstart this feature-implementation. 🚀🌟

**Comment by Megh2005** [comment]
Try to use next js as development framework and firebase as database

**Comment by Nkovaturient** [comment]
> @Nkovaturient
> 
> # `Don't forget to hit a message over here before sending the pull request`

Roger that!

**Comment by Megh2005** [comment]
## GUIDELINES
- **USE FIREBASE AS DATABASE**
- **YOU ARE ADVISED TO USE NEXT JS**
- **DON'T NEED TO THINK MUCH ABOUT FRONTEND, FOCUS ON THE BACKEND**
- **AS IT'S A MULTI BRANCH APP, WE ARE CREATING A NEW BRANCH FOR YOU `Med-o-Media`**
- **WE REALLY APPRECIATE YOU & WISH A THANK YOU FOR YOUR EFFORT**
## THANK YOU FROM TEAM **TECH JANTA PARTY**
![TJP](https://github.com/user-attachments/assets/121915a3-da00-4471-b66f-3d608403dc49)

**Comment by Nkovaturient** [comment]
> ## GUIDELINES
> * **USE FIREBASE AS DATABASE**
> * **YOU ARE ADVISED TO USE NEXT JS**
> * **DON'T NEED TO THINK MUCH ABOUT FRONTEND, FOCUS ON THE BACKEND**
> * **AS IT'S A MULTI BRANCH APP, WE ARE CREATING A NEW BRANCH FOR YOU `Med-o-Media`**
> * **WE REALLY APPRECIATE YOU & WISH A THANK YOU FOR YOUR EFFORT**
> 
> ## THANK YOU FROM TEAM **TECH JANTA PARTY**
> ![TJP](https://private-user-images.githubusercontent.com/147889330/373957611-121915a3-da00-4471-b66f-3d608403dc49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzI5OTcsIm5iZiI6MTcyODIzMjY5NywicGF0aCI6Ii8xNDc4ODkzMzAvMzczOTU3NjExLTEyMTkxNWEzLWRhMDAtNDQ3MS1iNjZmLTNkNjA4NDAzZGM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNjM4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTg1ZTc5Y2NkNTBmM2FjMjQzZWUzODNiYWNmYjUwMjJiODI1ZjdkNDZhNmExNTBlYWFkZjE0Y2ZlOTEwM2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GOV9_oflhxNzSvbNnC5o59vmZHFmGqKtbWbF3gK0WW0)

Most humbly, I feel honoured + I  am truly thankful to Team TJP (tan 90deg) for giving me this opportunity. 🌠
Surely, I shall commit myself to the above guidelines and dedicate in providing the desired results. 😺✨

**Comment by Megh2005** [comment]
Please send the .env example while giving PR

**Comment by Nkovaturient** [comment]
> Please send the .env example while giving PR

Okay. @Megh2005 
Also, I would like to clarify, do I need to implement firebase auth functionality as well?

**Comment by Megh2005** [comment]
> Okay. @Megh2005 Also, I would like to clarify, do I need to implement firebase auth functionality as well?

Yes, because you are creating a kind of medical news application, so we need to keep a track of all users

**Comment by Nkovaturient** [comment]
> > Okay. @Megh2005 Also, I would like to clarify, do I need to implement firebase auth functionality as well?
> 
> Yes, because you are creating a kind of medical news application, so we need to keep a track of all users

Aright!👩‍💻

**Comment by Megh2005** [comment]
Hey @Nkovaturient what's going on!!
Everything alright ??

**Comment by Nkovaturient** [comment]
Hello @Megh2005 , thanks for checking on! 😀💫

-Currently, working on filtering user preferences on health feeds after signup->surveyform->render preferences

so far, accomplished--

https://github.com/user-attachments/assets/1975f837-56ac-4142-a4d2-d9e22694c8e8

**Comment by Nkovaturient** [comment]
Also, @Megh2005 ,
In nextjs with app-routing model--how to ensure the navbar.js navigation through each web pages  properly..?

`<Link href="/healthNews">Hews</Link>`
-- healthNews page in "app/healthNews/page.js" rendered via "app/api/healthNews/route.js"

Can u once guide me thru the right structure..?

**Comment by Megh2005** [comment]
@iSubhamMani please look into the matter

**Comment by iSubhamMani** [comment]
@Nkovaturient can you describe the problem more you're facing? Email me: manisubham09@gmail.com

**Comment by iSubhamMani** [comment]
@Nkovaturient any updates?

**Comment by Nkovaturient** [comment]
Hello there! @iSubhamMani @Megh2005 , 
I have implemented the desired functionality and setup.

- .env example

1. NEXT_PUBLIC_NEWS_API
2. NEXT_PUBLIC_MEDIASTACK_API
3. NEXT_PUBLIC_FIREBASE_API_KEY
4. NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
5. NEXT_PUBLIC_FIREBASE_PROJECT_ID
6. NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
7. NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
8. NEXT_PUBLIC_FIREBASE_APP_ID
9. NEXT_PUBLIC_FIREBASE_MEASUREID

**Should I send a demo video before creating a PR?!**

**Comment by iSubhamMani** [comment]
Sure

**Comment by Nkovaturient** [comment]
https://github.com/user-attachments/assets/bbe0adf6-3b0b-47d2-9bfa-b8b8b68ba0e9

**Comment by iSubhamMani** [comment]
> **Check this out @iSubhamMani **
> 
>  Med-O-Media.preview.mp4

Is there an admin page where we can add news articles from? Other than that great work 👍

**Comment by Nkovaturient** [comment]
> > **Check this out @iSubhamMani **
> > Med-O-Media.preview.mp4
> 
> Is there an admin page where we can add news articles from? Other than that great work 👍

Great to hear you liked it.
As for admin/dashboard page, I havent integrated it.
 But, surely I can create it as you desire.

-  [Med-o-Media](https://med-o-media.vercel.app/)

**Comment by Nkovaturient** [comment]
Should I create a PR for now..? @iSubhamMani

**Comment by iSubhamMani** [comment]
@Nkovaturient Yes you can. I'll review it then you can start working on the admin page

**Comment by Nkovaturient** [comment]
> @Nkovaturient Yes you can. I'll review it then you can start working on the admin page

Alright!

**Comment by iSubhamMani** [comment]
Hey I reviewed the pr but it looks like the deployment failed. I can't
check the logs as it is deployed by Megh's acc and he is currently busy.

Can you try deploying it on your own vercel account? And see what are the
errors? Feel free to ask me out if you face any difficulties

**Comment by iSubhamMani** [comment]
Okay my bad let me see

**Comment by Megh2005** [comment]
@Nkovaturient 
Nice work 
A small request. Can you please upload your full code in a Google drive and send it to iammeghdeb@gmail.com giving me the access 
It will be very helpful for us

**Comment by Megh2005** [comment]
Please share the original `.env` file also. We promise you that we will not populate your database 
😊😊

**Comment by Megh2005** [comment]
No not like that
We will test it in our system and then if required we have to deploy it using some DevOps (Cloud) services

**Comment by Nkovaturient** [comment]
> No not like that We will test it in our system and then if required we have to deploy it using some DevOps (Cloud) services

Hello @Megh2005 ,
Kindly check your gmail. I have sent the updates!

**Comment by Megh2005** [comment]
Thank you for your contribution 
I am closing this issue
