### ISSUE TITLE
Add Cookies pop-up on landing to the website

### ISSUE THREAD

**Issue by Ashwinib26** [Megh2005/Med-o-Next#39]
Adding a cookies pop-up on the landing page is a common practice to inform users about data collection and obtain consent for tracking or storing cookies. This pop-up usually appears as a small modal or banner at the bottom or top of the webpage, displaying a message like, "This site uses cookies to improve your experience. By using our site, you agree to our Privacy Policy." The pop-up should also include buttons like "Accept", "Decline", or "Manage Preferences", allowing users to control their cookie settings.

**Comment by Megh2005** [comment]
The landing page is under construction by someone
