### ISSUE TITLE
Make the Website Responsive for the Mobile Verison 

### ISSUE THREAD

**Issue by rajatsinghal02** [Megh2005/Med-o-Next#46]
I want to make the website more beautiful in the mobile version by provide proper spacing to each section and the text so that user can easily catch and understand.

![Screenshot_20241008_014048.jpg](https://github.com/user-attachments/assets/febe66bc-7ff6-4a5d-9184-0e4bf7f28b24)

@Megh2005 Please assign this issue to me under gssoc-extd and hacktoberbest with the levels attached.

**Comment by Megh2005** [comment]
Someone is rebuilding the entire Landing page 
So this issue is not relevant anymore
