### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by dev129** [Megh2005/Med-o-Next#50]
### ISSUE NAME

Design Med-O-Shop

### ISSUE DESCRIPTION

When I click on the Med-O-Shop, the Link takes me nowhere hence, I would like to design the Med-O-Shop page for the users to easily Navigate among a large number of Medicines .

### YOUR APPROACH

I will firstly study some medical sites like 1mg, net meds etc. and design wireframe, then start design the prototype, with further modifications and  proper optimizing techniques using Link and Image components shall the Medicines be added.

### YOUR NAME

Devansh Vishwa 

### YOUR GITHUB PROFILE URL

https://github.com/dev129

**Comment by Megh2005** [comment]
No the Med-o-Shop page is good enough 
The buttons in the landing screen are not yet made active 
You can check Med-o-Shop from this [link](https://med-o-shop-1.onrender.com).
