### ISSUE TITLE
Implement Med-o-Shop page 

### ISSUE THREAD

**Issue by AmanKumar1115** [Megh2005/Med-o-Next#51]
### ISSUE NAME

Implement Med-o-Shop page

### ISSUE DESCRIPTION

your services card have Med-o-Shop option. I can create a page for it.

### YOUR APPROACH

I will create a frontend page for now.

1. Group categories like "Child Care," "Women Care," "Ayurveda," etc., using interactive cards with images for easy identification.
2. Add a "Featured Products" section highlighting top-selling items or new arrivals within each category.

For now I will use dummy data which will include image, name, price and discount offered for each product displayed in card format.

### YOUR NAME

Aman Kumar

### YOUR GITHUB PROFILE URL

https://github.com/AmanKumar1115

**Comment by Megh2005** [comment]
We already have a Med-o-Shop page 
**Check it [here](https://med-o-shop-1.onrender.com)**
