### ISSUE TITLE
set up backend for contact us form 

### ISSUE THREAD

**Issue by AyushSharma72** [Megh2005/Med-o-Next#53]
### ISSUE NAME

create contact us form

### ISSUE DESCRIPTION

i want to create a contact us form in the frontend 
and also set up  backend so that the user can contact you via email

### YOUR APPROACH

i will create a contact form in the frontend
![image](https://github.com/user-attachments/assets/b2a60851-34f9-4087-a931-db5a3cc102a8)

i will setup backend so that the user can contact you 

### YOUR NAME

Ayush sharma

### YOUR GITHUB PROFILE URL

https://github.com/AyushSharma72

**Comment by AyushSharma72** [comment]
_hey @Megh2005  thankyou for assigning but you know i have to create the whole backend from scratch _ which will take time 
also it require to make forntend form as well so please add level3 to this issue
i tell you why
-> i will create frontend for the form 
->then i will create the backend in nodejs from scratch 
-> then i have to create an api  to enable form send messages
-> then i have to connect the forntend form with backend 

i hp\ope you understand it is a long process which will take time so please assign level3 to this issue @Megh2005

**Comment by Megh2005** [comment]
No, just handle the responses using Firebase Realtime Database. Use the fetch method after copying the realtime database URI
It's just a 30 minute job 
You just need to create a contact form and connect it to Firebase Realtime Database 
Use React Hot Toast to show pop ups.
