### ISSUE TITLE
[ISSUE] : Implement a Sticky Navbar

### ISSUE THREAD

**Issue by rajgharat07** [Megh2005/Med-o-Next#56]
### ISSUE NAME

Improve Navbar

### ISSUE BRANCH

Improve Navbar

### ISSUE DESCRIPTION

The Navbar should remain visible at the top of the page as the user scrolls down, but currently, it scrolls away with the rest of the content. Implementing a sticky Navbar will enhance user navigation by keeping important links and options always accessible at the top. This feature is not working as expected, resulting in the Navbar not staying in place while scrolling.

Please assign this issue under Hacktoberfest and GSSOC

### YOUR APPROACH

To implement the sticky Navbar, I will:

- Add CSS Styles:
  - Apply the position: sticky property to the Navbar with a top value of 0px. This will ensure that the Navbar remains fixed at the top of the viewport as the user scrolls.

- Cross-Browser Testing:
  - Ensure compatibility across various browsers by testing how the sticky position behaves in Chrome, Firefox, Safari, and Edge.

- Responsive Design:
  - Check how the sticky Navbar responds on different screen sizes, especially on mobile devices, and adjust the layout accordingly if needed.

- Fix Overlapping Issues:
  - Ensure that the sticky Navbar doesn’t overlap with other content or create spacing issues when it becomes fixed.

### YOUR NAME

Raj Gharat

### YOUR GITHUB PROFILE URL

https://github.com/rajgharat07

**Comment by Megh2005** [comment]
Please fill the issue form properly 
Issue branch means in which branch you are facing the issue 
It's also written in the field description
