### ISSUE TITLE
The site icon on the browser tab.

### ISSUE THREAD

**Issue by akashdeepsingh283** [Megh2005/Med-o-Next#57]
### ISSUE NAME

The site icon on the browser tab.

### ISSUE BRANCH

Improve site UI.

### ISSUE DESCRIPTION

I will resolve this issue such that the site icon is visible on the browser tab.

### YOUR APPROACH

I will resolve this issue such that the site icon is visible on the browser tab.

### YOUR NAME

akashdeep singh

### YOUR GITHUB PROFILE URL

https://github.com/akashdeepsingh283

**Comment by Megh2005** [comment]
Please fill the issue form properly and raise the issue once again
