### ISSUE TITLE
Site Icon Missing from Browser Tab

### ISSUE THREAD

**Issue by akashdeepsingh283** [Megh2005/Med-o-Next#58]
### ISSUE NAME

Browser Tab Icon Not Displaying

### ISSUE BRANCH

feature/site-icon-update

### ISSUE DESCRIPTION

The site icon (favicon) does not appear on the browser tab when accessing the website. 

### YOUR APPROACH

To replace the Vercel favicon with your own, first create or prepare your favicon file (e.g., .ico, .png). Place it in the public directory of your project. Then, update the HTML <head> section with a <link> tag pointing to the favicon's path, like this:
<link rel="icon" href="/favicon.ico" type="image/x-icon">
Clear the browser cache, push the changes to your repository, and redeploy on Vercel to see your new favicon live.

### YOUR NAME

akashdeepsingh

### YOUR GITHUB PROFILE URL

https://github.com/akashdeepsingh283

**Comment by Megh2005** [comment]
Someone from our core team is already working on this feature 
We will look into it. Specific contributions not required as of now
