### ISSUE TITLE
[ISSUE] Improve Database Integration add Prisma

### ISSUE THREAD

**Issue by priyanshuverma-dev** [Megh2005/Med-o-Next#59]
### ISSUE NAME

Feature Add Prisma

### ISSUE BRANCH

Med-o-Chat

### ISSUE DESCRIPTION

Using raw mongodb is not efficient and scalable.
replace it with a strong ORM like `prisma`

### YOUR APPROACH

I will migrate complete chat system to `prisma`

### YOUR NAME

Priyanshu Verma

### YOUR GITHUB PROFILE URL

https://github.com/priyanshuverma-dev

**Comment by Megh2005** [comment]
Assigned to you with level 3 tag

**Comment by priyanshuverma-dev** [comment]
@Megh2005 The project has many clutters.
Can We use `next-auth` for authentication as we are using `mongodb` for database.
It makes no sense to  use firebase for only authentication

**Comment by priyanshuverma-dev** [comment]
Can you create I more issue to add `next-auth` and assign it to me. If you want

**Comment by Megh2005** [comment]
@iSubhamMani please look into this issue

**Comment by priyanshuverma-dev** [comment]
I am working on this issue will pull today

**Comment by Megh2005** [comment]
Not an issue 
Take your time
My collaborator @iSubhamMani will look into it
You can tag him whenever you are in requirement of help

**Comment by Megh2005** [comment]
Hey @priyanshuverma-dev 
Can you please fix the minor bugs present in the main branch
If you can , please raise an issue, we will give you a `level2` tag

**Comment by priyanshuverma-dev** [comment]
@Megh2005 what is the bug?

**Comment by Megh2005** [comment]
@iSubhamMani bro, please explain him the bugs
