### ISSUE TITLE
[Bug] add hover effect

### ISSUE THREAD

**Issue by Vinayyy19** [Megh2005/Med-o-Next#6]
### Description

When hovering over the sign-up button, the cursor does not change to a hand pointer as it does for other buttons.

### Steps to Reproduce

1. Visit the live link of the repo: [https://methodical-frame-405787.framer.app/#comp](https://methodical-frame-405787.framer.app/#comp)
2. Scroll down to the end of the page.
3. Hover over the sign-up button.

### Expected Behavior

When hovering over the sign-up button, the cursor should change to a hand pointer, similar to other buttons on the page.

### Actual Behavior

When hovering over the sign-up button, the cursor does not change to a hand pointer.

### Screenshots

![image](https://github.com/user-attachments/assets/e93a819b-5b16-4f80-9607-05134afd2e4b)

### Environment

- **OS:** Windows 10
- **Browser:** Chrome

**Comment by Vinayyy19** [comment]
Hi @Megh2005,
Can you add a label to this issue and assign it to me? I'm interested in fixing it.

**Comment by Megh2005** [comment]
Hi @Vinayyy19 
Don't look at the landing page
It is a static section only
Look into the branches 
If you can do any modification in it, please do ao
