### ISSUE TITLE
Add a Medical History page. 

### ISSUE THREAD

**Issue by aasiflm10** [Megh2005/Med-o-Next#64]
### ISSUE NAME

Medical History Page

### ISSUE BRANCH

Med-o-coach

### ISSUE DESCRIPTION

RIght now the website is in its primitive stage. We can add a View Previous History page which contains the previous History of the Patient. 

### YOUR APPROACH

Make modifications to the database. Add a notes Table. Fetch it for a particular user and display it in a separte history page.

### YOUR NAME

Aasif

### YOUR GITHUB PROFILE URL

https://github.com/aasiflm10

**Comment by aasiflm10** [comment]
@Megh2005 can i work on this issue under gssoc

**Comment by Megh2005** [comment]
I am assigning you a `level 3` mark as you need to do a lot of backend improvement in it

**Comment by aasiflm10** [comment]
thx. working on it.

**Comment by Megh2005** [comment]
If you face any issues, kind ly tag @Sayambar2004 as he is one of the builders

**Comment by aasiflm10** [comment]
@Sayambar2004 bro do you want the backend in  Nextjs only or express? Also, has anyone completed with Prisma integration. 
Also i saw you guys are thinking of having a firebase database. Firebase is a Nosql database, i think you guys should use SQL database ( relational database ) because this schema is going to have a lot of relations between tables. 
Please provide your input before i start implementing.

**Comment by aasiflm10** [comment]
yeah me too PostgreSQL is great.

**Comment by aasiflm10** [comment]
Work Completed. 
What have i done : 
1. added prisma ( postgreSQL ) database
2. Added addMedicalHistory and fetchMedicalHistory ( for a particular patient ) routes in nextjs backend.
3. Add frontend to add a medicalHistory page and show medical-history/:patientId page.

I Hope you like it. 
Here is a video displaying the working. 

[MedicalHistory.webm](https://github.com/user-attachments/assets/c3b148e4-1e30-48a7-8e5f-e38241dbf478)

Shall i generate a PR?

**Comment by aasiflm10** [comment]
@Megh2005  on which branch should i generate a PR on main or on med-o-coach ??

**Comment by Megh2005** [comment]
Send us the example secrets and give PR to Med-o-Coach

**Comment by Megh2005** [comment]
Please give the PR to the main branch directly
Sync it first and then push your PR

**Comment by aasiflm10** [comment]
If you have any issue in setup, feel free ask questions. I will be happy to help.

**Comment by aasiflm10** [comment]
Also can you please add hactoberfest tag @Megh2005  on my PR #83

**Comment by Megh2005** [comment]
Please one more PR to a branch that I am creating

**Comment by aasiflm10** [comment]
OK. Please add tags to PR also otherwise they wont count this PR.

**Comment by Megh2005** [comment]
I know, as I reverted your last PR, I can't label it
I will surely add the labels to your new PR

**Comment by aasiflm10** [comment]
@Megh2005 bro when are you going to create a new branch, so that i can send my PR?

**Comment by Megh2005** [comment]
It's already created 
You can check

**Comment by aasiflm10** [comment]
on which branch should i generate PR?

**Comment by Megh2005** [comment]
History Note

**Comment by aasiflm10** [comment]
bro i think you will have to open these PR #82  #83  because i am not able to understand how do i generate the new PR. 
Because when i am trying to push to a new branch ( everything is up to date ). If you know how to add a new PR with pervious commits please let me know. 
Thanks

**Comment by Megh2005** [comment]
Done
I reopened the PR and merged it
Giving you the proper tags
