### ISSUE TITLE
features

### ISSUE THREAD

**Issue by siddhant-2002** [Megh2005/Med-o-Next#66]
### ISSUE NAME

i want to create seperate pages for the footer links

### ISSUE BRANCH

main

### ISSUE DESCRIPTION

![image](https://github.com/user-attachments/assets/2201b72b-ff1f-4527-bdb5-8f1a60866928)

here footer link dosenot working 

### YOUR APPROACH

so i want to create pages give it header and footer and information related to the link

### YOUR NAME

siddhant deshmukh

### YOUR GITHUB PROFILE URL

https://github.com/siddhant-2002

**Comment by Megh2005** [comment]
Our core team is working on the main landing page
Don't need any further contribution in it
