### ISSUE TITLE
Issue Title: "Add 'Back to Top' Feature"

### ISSUE THREAD

**Issue by AswaniBolisetti** [Megh2005/Med-o-Next#67]
@Megh2005 
Issue Description: I would like to add a "Back to Top" feature to the website. This will include a button (with an up arrow) that allows users to quickly return to the top of the page after scrolling down, improving navigation and user experience.

Please assign this issue to me under the labels: level2, gssoc-ext, and hacktoberfest-accepted.

**Comment by Megh2005** [comment]
It's not a level 2 issue 
We can't allocate a **`level2`** tag for this

**Comment by AswaniBolisetti** [comment]
then please allocate as level 1, and give me a chance to contribute

**Comment by Megh2005** [comment]
Sure
