### ISSUE TITLE
[ISSUE]Empty Conversations State

### ISSUE THREAD

**Issue by teenagoyal21** [Megh2005/Med-o-Next#69]
### ISSUE NAME

The empty state shows "No conversations found" without any additional context or call to action.

### ISSUE BRANCH

Med-o-Chat

### ISSUE DESCRIPTION

The empty state shows "No conversations found" without any additional context or call to action.

### YOUR APPROACH

You could include a more helpful message or guide for first-time users. For example:
- Provide a button to "Start a New Conversation."
- Display recent contacts or suggestions for who the user might want to chat with (e.g., based on past interactions).

### YOUR NAME

Teena Goyal

### YOUR GITHUB PROFILE URL

https://github.com/teenagoyal21

**Comment by Megh2005** [comment]
It's not designed for doing chat with your contacts

**Comment by Megh2005** [comment]
No contribution is required fir thus issue
