### ISSUE TITLE
Add mini chatbot to the website

### ISSUE THREAD

**Issue by say-het** [Megh2005/Med-o-Next#72]
Hey @Megh2005  I have a great Idea.

 - Adding a mini AI based chatbot to website.

I am already working on this, please assign me this under gssoc-ext so I can raise a PR.

Little about me: I am an experienced contributor as I have successfully completed GSSoC-2024, Hacktoberfest-2020 and Hacktoberfest-2023.

**Comment by Megh2005** [comment]
Assigned

**Comment by Megh2005** [comment]
Merged successfully

Nice work !!!!
Best wishes from Team **Tech Janta Party**
![TJP](https://github.com/user-attachments/assets/69325cce-5b4a-4596-98eb-7b973d3b0dc8)
