### ISSUE TITLE
[ISSUE] Learn More" Button Not Visible Properly in Dark Mode

### ISSUE THREAD

**Issue by Priyanshu282003** [Megh2005/Med-o-Next#78]
### ISSUE NAME

"Learn More" Button Lacks Visibility in Dark Mode

### ISSUE BRANCH

dark-mode-ui-enhancement

### ISSUE DESCRIPTION

The "Learn More" button on the homepage is not clearly visible when viewed in dark mode. The button's white background blends with the overall dark theme, making it difficult for users to distinguish and interact with it.
![image](https://github.com/user-attachments/assets/a7ee7ca7-1d59-4429-b185-e8500f5cddaa)

### YOUR APPROACH

I will inspect the current CSS styling of the "Learn More" button in dark mode and modify the background color to provide better contrast against the dark background. If needed, I'll add a light border or shadow to improve visibility. I will also adjust hover and focus states for better interaction feedback. After testing the changes across different devices and browsers, I will push the updates to the dark-mode-ui-enhancement branch for review.

### YOUR NAME

Priyanshu Dubey

### YOUR GITHUB PROFILE URL

https://github.com/Priyanshu282003

**Comment by Megh2005** [comment]
Good job
