### ISSUE TITLE
The homepage can be made more user-friendly and engaging

### ISSUE THREAD

**Issue by ash-k121** [Megh2005/Med-o-Next#8]
We can add all the logos of  sub features like med-o-chat ,med-o-shop etc on the main page which will redirect to individual pages
![image](https://github.com/user-attachments/assets/e81850cf-ffd1-4c25-8ec5-46b5f1e2656f)
Full name : Ashmeet Kaur
What is your participant role? GSSOC EXT. 2024 Contributor
Please assign this to me.

**Comment by Megh2005** [comment]
Please provide me your email id, as I have built it on framer, I need to assign you as the collaborator there

**Comment by ash-k121** [comment]
> Please provide me your email id, as I have built it on framer, I need to assign you as the collaborator there

ashintern121@gmail.com

**Comment by Megh2005** [comment]
Have you received any access email ??
I hope you have...

**Comment by ash-k121** [comment]
yes thank you!

**Comment by Megh2005** [comment]
Please let me know @ash-k121 if you are done with the editing

**Comment by Megh2005** [comment]
@ash-k121 I am giving you a `Level 1` tag for this modification as it was a very minor change

**Comment by ash-k121** [comment]
I have create  modified homepage on framer

**Comment by Megh2005** [comment]
Just deploy it using the deployment button 
Send me the link and your github account link

**Comment by ash-k121** [comment]
https://azure-darling-860166.framer.app/modified
https://github.com/ash-k121

**Comment by Megh2005** [comment]
I will update the tables in the readme by tomorrow
