### ISSUE TITLE
Integrating Google Authentication using NextAuth.js to Med-o-Shop

### ISSUE THREAD

**Issue by sezallagwal** [Megh2005/Med-o-Next#80]
### ISSUE NAME

Google Authentication in Med-o-Shop 

### ISSUE BRANCH

Med-o-Shop

### ISSUE DESCRIPTION

The Med-o-Shop branch currently has dedicated signup and login pages; however, it does not support Google authentication. I propose integrating Google authentication using NextAuth.js to enhance user experience by allowing users to log in with their Google accounts.
Adding Google authentication will enhance security and improve the user experience, allowing users to sign in seamlessly without needing to create new accounts.

### YOUR APPROACH

I will integrate NextAuth.js into the Med-o-Shop branch to implement Google authentication.

Steps:

Install next-auth.js and its dependencies.
Configure NextAuth.js to use Google as an authentication provider.
Add a Sign in with Google button to the existing login page.
Manage user sessions using NextAuth.js to ensure users remain logged in securely.
Test the authentication flow to confirm that users can log in using their Google accounts without issues.

### YOUR NAME

Sezal Lagwal

### YOUR GITHUB PROFILE URL

https://github.com/sezallagwal

**Comment by Megh2005** [comment]
Please wait for the response from @iSubhamMani

**Comment by iSubhamMani** [comment]
@sezallagwal does nextauth work with express backend? If so you can surely start working on this issue
