### ISSUE TITLE
[ISSUE] Migrate Firebase auth to next-auth

### ISSUE THREAD

**Issue by priyanshuverma-dev** [Megh2005/Med-o-Next#84]
### ISSUE NAME

Migrate Firebase Auth to next-auth

### ISSUE BRANCH

Med-o-Chat

### ISSUE DESCRIPTION

We are using MongoDB to store data. So, I think we don't need firebase for only authentication.

### YOUR APPROACH

I will use `next-auth` and prisma to replace it. This issue will be the part of #59 
I am requesting to create a new branch on which I can push PR in checkpoints.
When Migration will be completed then you can merge that into main branch

### YOUR NAME

Priyanshu Verma

### YOUR GITHUB PROFILE URL

https://github.com/priyanshuverma-dev

**Comment by Megh2005** [comment]
No we are not ready to shift authentication method right now
