### ISSUE TITLE
[ISSUE] : Add a contact us page

### ISSUE THREAD

**Issue by amitroy-thedev** [Megh2005/Med-o-Next#85]
### ISSUE NAME

Add a contact us page

### ISSUE BRANCH

Med-o-next

### ISSUE DESCRIPTION

Currently there is no contact us page

### YOUR APPROACH

I will add a contact us page with a good looking UI

### YOUR NAME

Amit Roy

### YOUR GITHUB PROFILE URL

https://github.com/amitroy-thedev

**Comment by Megh2005** [comment]
- Don't add any seperate page
- Add separate section with the same theme
- Use firebase realtime database for ease
- Please active the subscribe field at the bottom if you can

**Comment by amitroy-thedev** [comment]
@Megh2005 Okay.. 
"Please activate the subscribe field at the bottom if you can" i haven't got this point would you elaborate

**Comment by amitroy-thedev** [comment]
@Megh2005 landing-page.tsx has many syntax error would you fix that

**Comment by Megh2005** [comment]
Fix them
I am giving you level 2

**Comment by Megh2005** [comment]
PR merged with proper labels
