### ISSUE TITLE
Add "About Page" page 

### ISSUE THREAD

**Issue by Sayali-740** [Megh2005/Med-o-Next#87]
### ISSUE NAME

 Missing "About Us" Page .

### ISSUE BRANCH

Main

### ISSUE DESCRIPTION

The website currently lacks an "About Us" page, which is essential for providing visitors with information about the project's mission, team, and background. An "About Us" page helps establish trust, enhances the user experience, and improves the overall transparency of the project.

### YOUR APPROACH

I will resolve this issue by Create a dedicated "About Us" page , Which can contain a brief overview of the project and its purpose.
Introducing the core contributors and their roles , the long-term goals of the project.

### YOUR NAME

Sayali More

### YOUR GITHUB PROFILE URL

https://github.com/Sayali-740

**Comment by Megh2005** [comment]
Already assigned to someone else
