### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by Sayali-740** [Megh2005/Med-o-Next#88]
### ISSUE NAME

 Missing Navigation Bar Page .

### ISSUE BRANCH

Main

### ISSUE DESCRIPTION

The website currently does not contain a navigation bar , A well-designed navbar can improve site navigation, user experience, and accessibility . A navbar can contain Home , About us , Contact us , login-signup etc . 

### YOUR APPROACH

I will create a semantic HTML <nav> element to house the navigation links. This will ensure that the site follows proper HTML5 structure and is accessible to screen readers . I will Style the navbar using CSS to match the existing theme of the website . I will ensure the navbar is responsive by utilizing media queries. 

### YOUR NAME

Sayali More

### YOUR GITHUB PROFILE URL

https://github.com/Sayali-740

**Comment by Megh2005** [comment]
This is assigned to someone else
