### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by manthanmk66** [Megh2005/Med-o-Next#89]
### ISSUE NAME

 Improve Hero Section Design and Chatbot Responsiveness

### ISSUE BRANCH

Med-o-AI

### ISSUE DESCRIPTION

The Hero Section currently lacks engaging content and needs a design enhancement to look visually appealing. Additionally, the chatbot is not fully responsive on mobile devices, resulting in poor user experience when interacting with it on smaller screens.

### YOUR APPROACH

Adjust the chatbot container to resize dynamically on mobile (using w-full, h-screen for mobile view).
Ensure the chatbot is easily scrollable and interaction buttons are accessible without overflow on small screens.
Test the chatbot on different devices to make sure it is fully responsive and provides a good user experience.

### YOUR NAME

Manthan Kasle

### YOUR GITHUB PROFILE URL

https://github.com/manthanmk66

**Comment by Megh2005** [comment]
Someone is already working on it
