### ISSUE TITLE
Med-o-Shop:  Add "Show Password" Icon in Password and Confirm Password Fields

### ISSUE THREAD

**Issue by Vishv0407** [Megh2005/Med-o-Next#9]
**Description**: On sign up/login page of Med-o-shop, The password and confirm password fields lack a "Show Password" option, making it hard for users to verify their input.

**Expected Behavior**: A "Show Password" icon (eye icon) should toggle the visibility of the password between hidden (masked) and visible (plain text) in both fields.

**Steps to Implement**:
Add an eye icon next to the password fields.
Implement a toggle function to switch between hidden and visible input.
Ensure proper styling and responsiveness.

Proposed Fix: Add a password visibility toggle for both fields, ensuring it works across all devices.

![image](https://github.com/user-attachments/assets/263b59a9-1123-443c-b29e-0ce110d1e130)

**Comment by Vishv0407** [comment]
I am interested to work on this issue.
Please assign me this issue and use relevant tags under Hacktober

**Comment by Vishv0407** [comment]
Can you please add tag of Hactoberfest and hacktoberfest-accepted.

**Comment by Vishv0407** [comment]
I am facing difficulty while cloning this repo, plaese guide me to clone.
git clone git@github.com:Megh2005/Med-o-Next.git

**Comment by Vishv0407** [comment]
I am facing difficulty in cloning this repo, can you please guide me to clone.

![image](https://github.com/user-attachments/assets/119143a4-4c41-48bd-a53a-d850e5103caf)

**Comment by PAVAN-VANAM** [comment]
hello @Vishv0407 

you are directly clone the owner github 
first fork the project and then project is under your github then clone the project

**Comment by Megh2005** [comment]
Hello @Vishv0407 is everything going good!? 
Please share some update. 
@iSubhamMani please guide him if he faces any problem as he is working on the page that was built by you
Try to use this command for installing packages.
```bash
npm install --force
```

**Comment by Megh2005** [comment]
> Hello @Vishv0407 is everything going good!? Please share some update. @iSubhamMani please guide him if he faces any problem as he is working on the page that was built by you Try to use this command for installing packages.
> 
> ```shell
> npm install --force
> ```
> 
> Also please let us know a fact : Are you from GSSOC Extended 2024??

**Comment by SanskariWolf** [comment]
Can you please assign this issue to me.

**Comment by Vishv0407** [comment]
Hello @Megh2005 @PAVAN-VANAM 

Thank you for your help to resolve my issue, I did successfully cloned repo and run project. Now I will start work on this and make a pull request with my solution.

Yes, I am a contributor of GSSOC'24 and also participated in Hactoberfest.

**Comment by Megh2005** [comment]
Okay , then I am giving you a **Level 2** label for this issue

**Comment by Vishv0407** [comment]
Thank you, Can you add labels for Hacktober'24 too. That labels are hactoberfest, hactoberfest-accepted.

**Comment by Megh2005** [comment]
All labels are added. Thank you for contribution
