### ISSUE TITLE
[ISSUE] Visibility Issue in Feature Section on Dark Mode

### ISSUE THREAD

**Issue by Priyanshu282003** [Megh2005/Med-o-Next#90]
### ISSUE NAME

Low Text Visibility in Feature Section on Dark Mode

### ISSUE BRANCH

feature-section-dark-mode

### ISSUE DESCRIPTION

There is a visibility issue in the "Our Features" section in dark mode. Specifically, the text for "Expert Consultations", "Medication Management", and "Medical Supplies" is hard to read due to insufficient contrast between the text color and the background. This affects the accessibility and user experience.

### YOUR APPROACH

To address this issue, I will first check the contrast between the text and background using a contrast tool. I plan to adjust the text color for "Expert Consultations," "Medication Management," and "Medical Supplies" to ensure better visibility against the dark background. If necessary, I will also tweak the background color. After testing the changes across devices and browsers for consistency and accessibility, I will ensure the solution meets WCAG standards before submitting a pull request.

### YOUR NAME

Priyanshu Dubey

### YOUR GITHUB PROFILE URL

https://github.com/Priyanshu282003

**Comment by Megh2005** [comment]
someone is working on it
