### ISSUE TITLE
Testimonials section

### ISSUE THREAD

**Issue by Ashwinib26** [Megh2005/Med-o-Next#92]
### ISSUE NAME

Add Testimonials section to the website

### ISSUE BRANCH

Main

### ISSUE DESCRIPTION

The Testimonials section will showcase authentic feedback from users, highlighting their experiences and satisfaction with the platform. These feedback demonstrate the platform's impact, encouraging new users to join and helps potential users feel confident in choosing the platform.

### YOUR APPROACH

This is just a sample image for testimonials section :

![image](https://github.com/user-attachments/assets/512cfdda-5c35-49d0-a9c8-314fc9dadba0)

### YOUR NAME

Ashwini Bisen

### YOUR GITHUB PROFILE URL

https://github.com/Ashwinib26//

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [ ] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by iSubhamMani** [comment]
@Ashwinib26 you're assigned

**Comment by Ashwinib26** [comment]
Thank You for assigning the issue. @iSubhamMani 
I will complete it shortly.

**Comment by Megh2005** [comment]
Hey @Ashwinib26 
We are facing some issues in Vercel deployment. Obviously that's not regarding your PR...
If you can fix it, we will give you **`level3`**

**Comment by Megh2005** [comment]
Any update ??
@Ashwinib26

**Comment by Ashwinib26** [comment]
Sorry @Megh2005 , but I won't be able to do that.
Thank you for the consideration.

**Comment by Megh2005** [comment]
Okay then we are closing this issue
