### ISSUE TITLE
[ISSUE] Improve Menu Toggle Button

### ISSUE THREAD

**Issue by RanitDERIA** [Megh2005/Med-o-Next#94]
### ISSUE NAME

[ISSUE] Improve Menu Toggle Button for Small Screens

### ISSUE BRANCH

main

### ISSUE DESCRIPTION

Currently, there is no menu toggle button available for small screens, which makes it difficult for users to navigate the website on mobile devices. This results in a poor user experience as users are unable to access the menu options when the screen size is reduced.

### YOUR APPROACH

I plan to address this issue by implementing a new menu toggle button that will:

- Allow users to easily access and navigate the menu on small screens.
- Include smooth animations for better user experience.
- Be responsive and compatible across various devices and browsers.

### YOUR NAME

RANIT DERIA

### YOUR GITHUB PROFILE URL

https://github.com/RanitDERIA

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [x] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by iSubhamMani** [comment]
@RanitDERIA you're assigned

**Comment by RanitDERIA** [comment]
Thank you for assigning this to me! I'll start working on the menu toggle issue and keep you updated on the progress.
