### ISSUE TITLE
[ISSUE]Add a scroll to top button 

### ISSUE THREAD

**Issue by Saransh-Jainbu** [Megh2005/Med-o-Next#95]
### ISSUE NAME

Improve User Interaction by implemention scroll to top button 

### ISSUE BRANCH

All

### ISSUE DESCRIPTION

I will add scroll to top button to whole site

### YOUR APPROACH

I will create button that when clicked will take the user to the top of the site , this button will only be visible when scrolled down. 

### YOUR NAME

Saransh Jain

### YOUR GITHUB PROFILE URL

https://github.com/Saransh-Jainbu

### Please select the applicable categories

- [ ] Hacktoberfest
- [X] GSSOC'24 Extended
- [ ] Read Documentation
- [ ] Want more credentials
- [ ] Other

**Comment by Megh2005** [comment]
Someone else is already working in this
