### ISSUE TITLE
[ISSUE] Adding a News Page called Med-o-News

### ISSUE THREAD

**Issue by J-B-Mugundh** [Megh2005/Med-o-Next#98]
### ISSUE NAME

Adding a News Page called Med-o-News

### ISSUE BRANCH

I request u to create a new branch called Med-o-News

### ISSUE DESCRIPTION

Adding a News Page called Med-o-News with News API

### YOUR APPROACH

Using News API and with either React JS or Next JS

### YOUR NAME

J B Mugundh

### YOUR GITHUB PROFILE URL

https://github.com/J-B-Mugundh

### Please select the applicable categories

- [X] Hacktoberfest
- [X] GSSOC'24 Extended
- [X] Read Documentation
- [X] Want more credentials
- [X] Other

**Comment by Megh2005** [comment]
Already done
We are working on deployment

**Comment by J-B-Mugundh** [comment]
@Megh2005 Do u guys have a map page to find nearby hospitals? If not, i can change this issue to that? Will that be fine?

**Comment by Megh2005** [comment]
I am working on it 
I am shifting the entire thing to Kotlin android app
Adding some very exclusive mapping features

**Comment by J-B-Mugundh** [comment]
> I am working on it I am shifting the entire thing to Kotlin android app Adding some very exclusive mapping features

Alright! Is there anything else I could work on?
