### ISSUE TITLE
UI Enhancements: Header, Footer, and Visual Improvements

### ISSUE THREAD

**Issue by Mallik-vinukonda** [Megh2005/Med-o-Next#99]
I noticed that the Med-O-Next website is currently missing a proper header and footer, which are essential for a cohesive user experience. I’d like to enhance the overall UI by adding a consistent header and footer, while also improving the visual design for a more polished and professional look. These changes will ensure better navigation and layout consistency across the site.

Let me know if you have any specific design preferences or requirements!

**Comment by krishna7602** [comment]
Please assign me this issue
